apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-webapp
  namespace: frontend-webapp
spec:
  selector:
    matchLabels:
      app: frontend-webapp
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: frontend-webapp
    spec:
      containers:
        - name: frontend-webapp-backend-container
          image: "{{ .Values.image.repository }}:{{ .Values.image_tag }}"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.2"
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 80
              protocol: TCP
