apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: frontend-app
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app-backend-container
          image: "{{ .Values.image.repository }}:{{ .Values.image_tag }}"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "0.2"
          ports:
            - containerPort: 80
              protocol: TCP
