apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  namespace: frontend-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: frontend-app
  type: LoadBalancer
