apiVersion: v1
kind: Service
metadata:
  name: frontend-webapp-service
  namespace: frontend-webapp
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend-webapp
  type: LoadBalancer
